### ISSUE TITLE
please verify if this works in CLion

### ISSUE THREAD

**Issue by nevion** [mprobst/ClangFormatIJ#4]
I have a fresh install of CLion, I am loading the plugin from disk and it is loaded successfully, but requires restart CLion.

I restart and the plugin is now gone from the plugin list.

Is there a dependency or something that this plugin requires or is it a comparability issue?

**Comment by mprobst** [comment]
Sorry, I have no idea about CLion, but I do not think there should be
anything special about it in this regard, as compared to other IntelliJ
distributions.

Jason Newton <notifications@github.com> schrieb am Sa., 23. Sep. 2017 um
05:55 Uhr:

**Comment by rinick** [comment]
it works, but it crashs my clion all the time, once it even crashs windows 10! YES, I'm talking about that blue screen.

**Comment by mprobst** [comment]
@rinick you must be having different issues, clang-format emphatically shouldn't be able to crash your computer, let alone your IDE :-)
